"""Add quotation snapshots

Revision ID: 1279141485af
Revises: 7f7f5c1e07ce
Create Date: 2026-09-03 05:07:54.020861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1279141485af'
down_revision: Union[str, Sequence[str], None] = '7f7f5c1e07ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_snapshots_id'), 'quotation_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_quotation_snapshots_quotation_id'), 'quotation_snapshots', ['quotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_snapshots_quotation_id'), table_name='quotation_snapshots')
    op.drop_index(op.f('ix_quotation_snapshots_id'), table_name='quotation_snapshots')
    op.drop_table('quotation_snapshots')
    # ### end Alembic commands ###
