"""add project item dimensions

Revision ID: 353e048b5cf6
Revises: 81e08764241e
Create Date: 2026-09-01 21:39:03.675030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353e048b5cf6'
down_revision: Union[str, Sequence[str], None] = '81e08764241e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_items', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('project_items', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_items', 'height')
    op.drop_column('project_items', 'width')
    # ### end Alembic commands ###
