"""add quoted price to projects

Revision ID: 7830c5710bc0
Revises: d2caf881143d
Create Date: 2026-09-02 00:19:51.499735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7830c5710bc0'
down_revision: Union[str, Sequence[str], None] = 'd2caf881143d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('quoted_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'quoted_price')
    # ### end Alembic commands ###
