"""add project item pricing fields

Revision ID: adb9934c78df
Revises: 353e048b5cf6
Create Date: 2026-09-01 22:01:43.234792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb9934c78df'
down_revision: Union[str, Sequence[str], None] = '353e048b5cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_items', sa.Column('material', sa.String(length=100), nullable=True))
    op.add_column('project_items', sa.Column('profile', sa.String(length=100), nullable=True))
    op.add_column('project_items', sa.Column('glass_type', sa.String(length=100), nullable=True))
    op.add_column('project_items', sa.Column('unit_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_items', 'unit_price')
    op.drop_column('project_items', 'glass_type')
    op.drop_column('project_items', 'profile')
    op.drop_column('project_items', 'material')
    # ### end Alembic commands ###
