"""add project expenses table

Revision ID: d2caf881143d
Revises: adb9934c78df
Create Date: 2026-09-01 23:37:31.610892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2caf881143d'
down_revision: Union[str, Sequence[str], None] = 'adb9934c78df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_expenses_id'), 'project_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_project_expenses_project_id'), 'project_expenses', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_expenses_project_id'), table_name='project_expenses')
    op.drop_index(op.f('ix_project_expenses_id'), table_name='project_expenses')
    op.drop_table('project_expenses')
    # ### end Alembic commands ###
